### ISSUE TITLE
Implement Linux framebuffer backend

### ISSUE THREAD

**Issue by jserv** [sysprog21/mado#3]
Mado should provide a Linux framebuffer/DRM backend, which is more suitable for embedded systems. In addition, the use of the Linux input subsystem is crucial for integration.

Reference:
* [Back to the Linux Framebuffer!](https://archive.fosdem.org/2020/schedule/event/fbdev/), FOSDEM 2020
* [yamui](https://github.com/sailfishos/yamui)
* [DirectFB2](https://directfb2.github.io/)
* [Playground with the Linux Framebuffer](https://github.com/obvMellow/linuxfb)

**Comment by jserv** [comment]
With the inclusion of [kconfiglib](https://pypi.org/project/kconfiglib/), the build system is now fully configurable like "menuconfig" when building the Linux kernel. This flexibility is also useful for developers to integrate additional backends such as Linux framebuffer and DRM device support. (#18)

**Comment by jserv** [comment]
LVGL implements both Linux framebuffer and DRM support. See:
* [docs/integration/driver/display/fbdev.rst](https://github.com/lvgl/lvgl/blob/master/docs/integration/driver/display/fbdev.rst)
* [lv_port_linux](https://github.com/lvgl/lv_port_linux)
* [src/drivers/display/drm/lv_linux_drm.h](https://github.com/lvgl/lvgl/blob/master/src/drivers/display/drm/lv_linux_drm.h)
* [src/drivers/display/drm/lv_linux_drm.c](https://github.com/lvgl/lvgl/blob/master/src/drivers/display/drm/lv_linux_drm.c)
* [src/drivers/display/fb/lv_linux_fbdev.h](https://github.com/lvgl/lvgl/blob/master/src/drivers/display/fb/lv_linux_fbdev.h)
* [src/drivers/display/fb/lv_linux_fbdev.c](https://github.com/lvgl/lvgl/blob/master/src/drivers/display/fb/lv_linux_fbdev.c)

[awtk-linux-fb](https://github.com/zlgopen/awtk-linux-fb) is more complete.

**Comment by shengwen-tw** [comment]
Add information of Virtual Terminal (Console) as the Linux framebuffer/DRM backend should also take care of the VT switching:
* [Virtual console - Wikipedia](https://en.wikipedia.org/wiki/Virtual_console)
* [Linux console - Wikipedia](https://en.wikipedia.org/wiki/Linux_console)

**Comment by shengwen-tw** [comment]
In GNU/Linux, the user can switch between different virtual terminals using `Ctrl+Alt+Fn`. The first virtual terminal (VT1, accessed with `Ctrl+Alt+F1`) is typically used by the graphical desktop environment.

We should deactivate the virtual terminal when `Mado` is running and restore it in opposite case.

**Comment by jserv** [comment]
[drm-framebuffer](https://github.com/embear-engineering/drm-framebuffer) is a simple application which can be used to test a Linux DRM device.

**Comment by shengwen-tw** [comment]
[Frame Buffer device internals](https://docs.kernel.org/fb/internals.html)

**Comment by shengwen-tw** [comment]
[pslash](https://www.artila.com/download/9G45/Linux/Example/psplash/psplash-console.c), a lightweight framebuffer splashscreen for embedded devices, provides good reference for virtual terminal (VT) management.

**Comment by jserv** [comment]
Let's focus on Linux framebuffer support for now. DRM support can be considered as a follow-up once the non-SDL display target and VT implementation are merged.

**Comment by shengwen-tw** [comment]
DirectFB uses the **event device** and **udev** to manage Human Interface Devices (HIDs), in which udev is for handling device plug-in and removal.

Let's handle the mouse events (i.e., `EV_REL` and `EV_ABS`) first by reading all event devices (i.e., `/dev/input/eventX`) using `poll()` (or any suitable APIs) in a thread and later adding support for udev.

* [edev thread in DirectFB](https://github.com/directfb2/DirectFB2/blob/master/inputdrivers/linux_input/linux_input.c#L884)
* [udev thread in DirectFB]( https://github.com/directfb2/DirectFB2/blob/master/inputdrivers/linux_input/linux_input.c#L1692)

**Comment by jserv** [comment]
> Let's handle the mouse events (i.e., `EV_REL` and `EV_ABS`) first by reading all event devices (i.e., `/dev/input/eventX`) using `poll()` (or any suitable APIs) in a thread and later adding support for udev.

Related: #4

**Comment by jserv** [comment]
According to [Linux 6.12 To Optionally Display A QR Code During Kernel Panics](https://www.phoronix.com/news/Linux-6.12-DRM-Panic-QR-Code), a new feature allows the display of a QR code within the DRM panic handler infrastructure when a Linux kernel panic occurs. We could consider integrating parts of the Mado codebase into the Linux kernel (as a module) to enhance text rendering capabilities. As a graphical library and window system, Mado does not rely on floating-point operations, making it suitable for Linux kernel integration where no FPU is available.
