### ISSUE TITLE
Implement VNC-compatible backend

### ISSUE THREAD

**Issue by jserv** [sysprog21/mado#32]
The [Qt VNC server](https://doc.qt.io/QtVNCServer/) uses the [Remote Frame Buffer](https://en.wikipedia.org/wiki/RFB_protocol) (RFB) protocol to share graphics and input between the server and one or more remote VNC-compatible clients. A common use case is to share parts of a Qt Quick application with a remote user or screen using the QtVncServer module. The remote user can view and interact with the application through VNC-compatible client software.

If we implement a VNC-compatible backend for Mado, we can create a similar scenario inspired by the Qt VNC server. This would serve as a minimalist backend for purposes such as performing memory analysis with Valgrind on Linux without needing to start in [framebuffer console](https://docs.kernel.org/fb/fbcon.html) (fbcon) mode (#15), and providing a reference implementation for remote desktop support.

Reference:
* [Qt VNC Server](https://doc.qt.io/QtVNCServer/)
* [VNC for Qt/Quick on EGLFS](https://github.com/uwerat/vnc-eglfs)
* [AWTK-VNC](https://github.com/zlgopen/awtk-vnc)

**Comment by shengwen-tw** [comment]
[Remote Frame Buffer (RFB) specification](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst)

**Comment by jserv** [comment]
The C library [libvncserver](https://github.com/LibVNC/libvncserver) offers extensive functionality for implementing VNC server or client capabilities in software projects. However, its GNU GPL licensing requires that any programs using it must also be released under the GNU GPL, as they're considered derivative works. In contrast, [neatvnc](https://github.com/any1/neatvnc) is a VNC server library designed for speed and simplicity, distributed under the more permissive ISC license. QEMU incorporates a custom-built [VNC display driver](https://github.com/qemu/qemu/blob/master/ui/vnc.c), which is made available under the permissive MIT license.
