### ISSUE TITLE
Refine event handling

### ISSUE THREAD

**Issue by jserv** [sysprog21/mado#4]
The internal event handling relied on the poll(2) for monitoring X11 events via I/O multiplexing. However, for backends such as SDL, this manipulation causes problems since the internal file descriptors associated with underlying system events are hidden and not exposed. Thus, we should avoid polling the file descriptors. Instead, let the backend handle the event loop when possible. See commit e935b0d4e505729b2b931934ecb729b0015d88f8 .

For #3, we may provide poll(2) based mechanism to monitor events when requested.

**Comment by shengwen-tw** [comment]
Reference for implementing Coroutine in C:
https://github.com/shengwen-tw/coroutine_c
