### ISSUE TITLE
Incorrect background pixmap rendering

### ISSUE THREAD

**Issue by jserv** [sysprog21/mado#5]
The background is set to a pixmap with ARGB32 color space. However, the rendering is incorrect compared to the image in `assets/tux.png`. This issue can be reproduced with the SDL backend.

**Comment by marvin0102** [comment]
The PNG file seems to be read as BGR format. Is the rendering correct on linux?

**Comment by marvin0102** [comment]
Also, if the color type of the PNG file is RGBA, the rendering is wrong too.

**Comment by jserv** [comment]
> The PNG file seems to be read as BGR format. Is the rendering correct on linux?

The screenshot below shows TWIN attempting to render the scaled PNG file (left), while the original PNG file is rendered by the ImageMagick tool (right).

<img width="1124" alt="comparison" src="https://github.com/user-attachments/assets/6a22328b-9065-4d0c-a32f-8792074b52f5">

**Comment by marvin0102** [comment]
The PNG file seems have different rendering on mac and linux.
The screenshot below is the result of TWIN running on mac.
<img width="1249" alt="截圖 2024-07-18 上午11 19 22" src="https://github.com/user-attachments/assets/0baa4f09-c219-4e4f-91c9-ca450f9be2e5">

**Comment by jserv** [comment]
The proposed changes to fix the background rendering issue:
```diff
diff --git a/src/image-png.c b/src/image-png.c
index e69f17e..2d7d12f 100644
--- a/src/image-png.c
+++ b/src/image-png.c
@@ -17,6 +17,23 @@ static void _twin_png_read(png_structp png, png_bytep data, png_size_t size)
         png_error(png, "end of file !\n");
 }
 
+/* FIXME: Utilize pixman or similar accelerated routine to convert */
+static void _convertBGRtoARGB(uint8_t *data, int width, int height)
+{
+    for (int y = 0; y < height; y++) {
+        for (int x = 0; x < width; x++) {
+            int index = (y * width + x) * 4;
+            uint8_t b = data[index];
+            uint8_t g = data[index + 1];
+            uint8_t r = data[index + 2];
+            data[index] = 255; /* Alpha */
+            data[index + 1] = r;
+            data[index + 2] = g;
+            data[index + 3] = b;
+        }
+    }
+}
+
 twin_pixmap_t *twin_png_to_pixmap(const char *filepath, twin_format_t fmt)
 {
     uint8_t signature[8];
@@ -83,7 +100,7 @@ twin_pixmap_t *twin_png_to_pixmap(const char *filepath, twin_format_t fmt)
         goto bail_free;
     case TWIN_ARGB32:
         if (ctype == PNG_COLOR_TYPE_RGB)
-            png_set_filler(png, 0xff, PNG_FILLER_BEFORE);
+            png_set_filler(png, 0xff, PNG_FILLER_AFTER);
         if (ctype == PNG_COLOR_TYPE_GRAY || ctype == PNG_COLOR_TYPE_GRAY_ALPHA)
             png_set_gray_to_rgb(png);
 
@@ -109,8 +126,12 @@ twin_pixmap_t *twin_png_to_pixmap(const char *filepath, twin_format_t fmt)
 
     png_read_end(png, NULL);
 
-    if (fmt == TWIN_ARGB32)
+    if (fmt == TWIN_ARGB32) {
+        /* Convert from BGR to ARGB if necessary */
+        if (ctype == PNG_COLOR_TYPE_RGB || ctype == PNG_COLOR_TYPE_RGB_ALPHA)
+            _convertBGRtoARGB(pix->p.b, width, height);
         twin_premultiply_alpha(pix);
+    }
 
 bail_free:
     free(rowp);
```

@marvin0102, Once you have tested with more PNG files and confirmed the functionality of the proposed changes, send a pull request to close the issue.

**Comment by jserv** [comment]
Close via #10
