### ISSUE TITLE
Add TinyVG Support

### ISSUE THREAD

**Issue by jserv** [sysprog21/mado#71]
With the introduction of the GIF image decoder and animation support (#40) contributed by @ndsl7109256, it is now time to move forward with implementing [TinyVG](https://tinyvg.tech/) -- a compact vector graphics format designed as a lightweight alternative to SVG. The [TinyVG specification](https://github.com/TinyVG/specification) is only 14 pages long, in stark contrast to the SVG 1.1 spec, which spans 260 pages (not including dependencies like CSS, XML, and ECMAScript). TinyVG achieves simplicity without sacrificing core vector graphics capabilities, making it ideal for embedded systems with limited resources.

Integrating TinyVG support into Mado could offer efficient vector graphics rendering with lower memory and computational overhead than SVG. Here are key areas to address:
1. File Parsing: Implement a TinyVG file parser to read the binary format efficiently, ensuring the parsing adheres to TinyVG’s specification.
2. Rendering Engine: Adapt Mado’s rendering pipeline to handle TinyVG graphics primitives (paths, lines, polygons, etc.) and basic fills.
3. Performance Considerations: Ensure smooth performance on resource-constrained devices.
4. Testing: Prepare sample TinyVG files and conduct visual tests to verify rendering accuracy and performance benefits.

The article [An Introduction to TinyVG in C](https://www.codeproject.com/Articles/5389336/An-Introduction-to-TinyVG-in-C) uses [PlutoVG](https://github.com/sammycage/plutovg) to render TinyVG, and since the vector graphics operations in PlutoVG closely align with those in Mado, it should be feasible to port the sample C-based TinyVG decoder to Mado as a new image loader.

Supporting TinyVG in Mado aligns well with the project’s goals by delivering essential vector graphics with minimal overhead.

Reference:
* [A vector format for Flutter](https://docs.google.com/document/d/1YWffrlc6ZqRwfIiR1qwp1AOkS9JyA_lEURI8p5PsZlg/edit?usp=sharing)
* [TinyVG software development kit](https://github.com/TinyVG/sdk)
* [intvg](https://github.com/mhfan/intvg): [TinyVG](https://tinyvg.tech/) image parser & renderer in Rust

**Comment by ndsl7109256** [comment]
Can I take this issue?

**Comment by jserv** [comment]
> Can I take this issue?

Go ahead.

**Comment by ndsl7109256** [comment]
It seems that TinyVG provides an SDK that includes the ability to convert a TinyVG file into a bitmap giving a specified size. In that case, do we still need to implement rendering ourselves using Mado’s rendering pipeline? If so, perhaps we could start by implementing functions to render polygons and fill them with gradient colors?

**Comment by jserv** [comment]
> It seems that TinyVG provides an SDK that includes the ability to convert a TinyVG file into a bitmap giving a specified size. In that case, do we still need to implement rendering ourselves using Mado’s rendering pipeline? If so, perhaps we could start by implementing functions to render polygons and fill them with gradient colors?

TinyVG SDK focuses on conversion at the moment, but we do need the proper renderer for TinyVG, making use of the vector graphics operation.

**Comment by jserv** [comment]
[GFX](https://honeythecodewitch.com/gfx/docs/index.md) implements TinyVG: [src/gfx_tvg.cpp](https://github.com/codewitch-honey-crisis/gfx/blob/master/src/gfx_tvg.cpp) renderer.

**Comment by jserv** [comment]
[ctx](https://ctx.graphics/) implements TinyVG renderer: [src/tinyvg.c](https://github.com/facsimiles/ctx/blob/dev/src/tinyvg.c)

**Comment by jserv** [comment]
[Ladybird](https://ladybird.org/), a truly independent web browser, implements TinyVG image loader: [Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp](https://github.com/LadybirdBrowser/ladybird/blob/master/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp)
